import { Request, Response } from "express";
import ChatbotConfig from "../../shared/database/models/ChatbotConfig";
import Company from "../../shared/database/models/Company";

export async function getConfig(req: Request, res: Response) {
  let config = await ChatbotConfig.findOne({
    where: { companyId: req.companyId },
  });

  if (!config) {
    config = await ChatbotConfig.create({
      companyId: req.companyId,
      isActive: true,
      aiProvider: "openai",
      aiModel: "gpt-4o",
      systemPrompt:
        "Você é um assistente de atendimento ao cliente. Responda de forma educada e profissional.",
      temperature: 0.7,
      maxTokens: 2048,
      knowledgeBase: "",
    });
  }

  res.json({ config });
}

export async function updateConfig(req: Request, res: Response) {
  const data = req.body;

  let config = await ChatbotConfig.findOne({
    where: { companyId: req.companyId },
  });

  if (!config) {
    config = await ChatbotConfig.create({
      companyId: req.companyId,
      ...data,
    });
  } else {
    await config.update(data);
  }

  res.json({ config });
}

export async function generatePrompt(req: Request, res: Response) {
  const company = await Company.findByPk(req.companyId);
  if (!company) return res.status(404).json({ error: "Company not found" });

  const { businessArea, businessHours, productsServices } = company;
  const name = company.name || "Minha Empresa";

  const horario = businessHours || "seg a sex das 8h as 18h";
  const segmento = businessArea || "nosso segmento";
  const produtos = productsServices || "nossos produtos e servicos";

  const systemPrompt = `Você é o assistente virtual oficial da ${name}, especializado em atendimento ao cliente.

INFORMAÇÕES DA EMPRESA:
- Nome: ${name}
- Segmento: ${segmento}
- Horário de funcionamento: ${horario}
- Produtos/Serviços: ${produtos}

REGRAS DE ATENDIMENTO:
1. Seja educado, profissional e objetivo.
2. Sempre se identifique como assistente da ${name}.
3. Fora do horário de funcionamento, informe que o atendimento será retomado no próximo dia útil.
4. Se não souber responder algo, avise o cliente que vai transferir para um atendente humano.
5. Nunca invente informações. Se não tiver a resposta, peça para o cliente aguardar o atendente.
6. Responda em português do Brasil.`;

  const knowledgeBase = `EMPRESA: ${name}
SEGMENTO: ${segmento}
HORÁRIO DE FUNCIONAMENTO: ${horario}
PRODUTOS/SERVIÇOS:
${produtos}

INSTRUÇÕES:
- Atender clientes via WhatsApp
- Tirar dúvidas sobre produtos e serviços
- Agendar visitas e reuniões
- Encaminhar para atendente humano quando necessário`;

  let config = await ChatbotConfig.findOne({
    where: { companyId: req.companyId },
  });

  if (!config) {
    config = await ChatbotConfig.create({
      companyId: req.companyId,
      isActive: true,
      aiProvider: "openai",
      aiModel: "gpt-4o",
      systemPrompt,
      knowledgeBase,
      temperature: 0.7,
      maxTokens: 2048,
    });
  } else {
    await config.update({ systemPrompt, knowledgeBase });
  }

  await company.update({ promptAutoGenerated: true });

  res.json({ config, generated: true });
}
